[package]
name = "yevis"
version = "0.1.0"
authors = ["DBCLS (Database Center for Life Science)"]
edition = "2021"
readme = "https://github.com/ddbj/yevis-cli/README.md"
repository = "https://github.com/ddbj/yevis-cli"
license = "Apache-2.0"

[dependencies]
structopt = "0.3.25"
url = "2.2.2"
anyhow = "1.0.52"