[package]
authors = ["DBCLS (Database Center for Life Science)"]
edition = "2021"
license = "Apache-2.0"
name = "yevis"
readme = "https://github.com/ddbj/yevis-cli/README.md"
repository = "https://github.com/ddbj/yevis-cli"
version = "0.1.0"

[dependencies]
anyhow = "1.0.52"
regex = "1.5.4"
reqwest = {version = "0.11.8", features = ["blocking", "json"]}
serde = {version = "1.0.132", features = ["derive"]}
serde_yaml = "0.8.23"
structopt = "0.3.25"
url = {version = "2.2.2", features = ["serde"]}
