[package]
authors = ["DDBJ(DNA Data Bank of Japan)"]
edition = "2018"
license = "Apache-2.0"
name = "yevis"
readme = "https://github.com/ddbj/yevis-cli/README.md"
repository = "https://github.com/ddbj/yevis-cli"
version = "0.1.2"

[dependencies]
anyhow = {version = "1.0.52", features = ["backtrace"]}
base64 = "0.13.0"
colored = "2.0.0"
dotenv = "0.15.0"
gh-trs = "1.1.6"
log = "0.4.14"
regex = "1.5.4"
reqwest = {version = "0.11.8", features = ["blocking", "json", "multipart"]}
rust-crypto = "0.2.36"
serde = {version = "1.0.132", features = ["derive"]}
serde_json = "1.0.74"
serde_yaml = "0.8.23"
structopt = "0.3.25"
url = {version = "2.2.2", features = ["serde"]}
uuid = {version = "0.8.2", features = ["serde", "v4"]}
