version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yevis-cli
    container_name: yevis-cli
    volumes:
      - ${PWD}:/app
    environment:
      - RUST_BACKTRACE=1
    restart: on-failure
    working_dir: /app
    command: [ "sleep", "infinity" ]
