version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yevis-cli
    container_name: yevis-cli
    volumes:
      - ${PWD}:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RUST_BACKTRACE=1
      - SAPPORO_RUN_DIR=${PWD}/run
    restart: on-failure
    working_dir: /app
    command: [ "sleep", "infinity" ]
    networks:
      - yevis-network

networks:
  yevis-network:
    name: yevis-network
