version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: yevis-cli-dev
    container_name: yevis-cli-dev
    volumes:
      - ${PWD}:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RUST_BACKTRACE=1
      - YEVIS_DEV=1
      - SAPPORO_RUN_DIR=${PWD}/sapporo_run
    restart: on-failure
    working_dir: /app
    command: [ "sleep", "infinity" ]
    networks:
      - gh-trs-network

networks:
  gh-trs-network:
    name: gh-trs-network
