name: build_binary

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "Cargo.**"
  workflow_dispatch: {}

jobs:
  build-yevis:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Build yevis binary (x86_64)"
        run: docker run --rm -it -v "$(pwd)":/home/rust/src messense/rust-musl-cross:x86_64-musl cargo build --release --target x86_64-unknown-linux-musl

      - name: "Build yevis binary (arm64)"
        run: docker run --rm -it -v "$(pwd)":/home/rust/src messense/rust-musl-cross:aarch64-musl cargo build --release --target aarch64-unknown-linux-musl

      - name: "Upload yevis binary (x86_64)"
        uses: actions/upload-artifact@v3
        with:
          name: yevis_x86_64
          path: target/x86_64-unknown-linux-musl/release/yevis

      - name: "Upload yevis binary (arm64)"
        uses: actions/upload-artifact@v3
        with:
          name: yevis_arm64
          path: target/aarch64-unknown-linux-musl/release/yevis
